version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - "5555:5432"
    restart: always
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./nc_data:/var/lib/postgresql/data:rw
  no_codb:
    image: nocodb/nocodb:0.96.4
    ports:
      - "8080:8080"
    depends_on:
      - postgres

    restart: always
    volumes:
      - ./nc_data:/usr/app/data
    environment:
      NC_DB: "pg://host.docker.internal:5432?u=postgres&p=postgres&d=root_db"